### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by RhettCreighton** [ooni/go-libtor#6]
Thank you for keeping the updates going.  
I have the ipsn library working with tor 0.3.5, hoping to get this with updates for 0.4.7 and other cross platform support you are working on.
For some reason, I get this when I try to drop in replace for

https://github.com/ipsn/go-libtor

```
go build
# github.com/ooni/go-libtor/libtor
../../go/pkg/mod/github.com/ooni/go-libtor@v1.1.8/libtor/libtor.go:8:10: fatal error: tor_api.h: No such file or directory
    8 | #include <tor_api.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by hkparker** [comment]
Seeing this as well in arch linux.  Is is expected that tor should already be installed on the system to provide header files that are not included in this repository, or is this missing?
